"""
Generate Sprint_4.docx — final sprint deliverable.
Matches the style of Sprint 1/2/3 docs and incorporates:
  • Sprint goal aligned with the Proposal (Sec 6 timeline → Sprint 4 = KPIs + testing + tuning)
  • Sprint 3 "Next Sprint Plan" tasks (Export, Audit Log, KPI Dashboard, Tests)
  • Embedded charts and diagrams generated by generate_sprint4_assets.py
"""
import os
from datetime import datetime

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.shared import Pt, RGBColor, Cm, Inches
from docx.oxml.ns import qn, nsmap
from docx.oxml import OxmlElement

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, "sprint4_assets")
OUT_PATH = os.path.join(os.path.dirname(HERE), "Sprint 4.docx")

# Brand colors (match the React frontend)
PRIMARY_BLUE = RGBColor(0x1F, 0x4E, 0x79)
ACCENT_INDIGO = RGBColor(0x63, 0x66, 0xF1)
TEXT_DARK = RGBColor(0x1F, 0x29, 0x37)
TEXT_MUTED = RGBColor(0x6B, 0x72, 0x80)
SUCCESS = RGBColor(0x06, 0x5F, 0x46)
WARNING = RGBColor(0x92, 0x40, 0x0E)


# ─── Helpers ────────────────────────────────────────────────────────────────

def shade_cell(cell, hex_color):
    """Apply a background fill color to a table cell."""
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tc_pr.append(shd)


def add_horizontal_rule(paragraph):
    """Insert a 1pt horizontal rule below a paragraph."""
    p_pr = paragraph._p.get_or_add_pPr()
    p_bdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "8")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "1F4E79")
    p_bdr.append(bottom)
    p_pr.append(p_bdr)


def H1(doc, text, color=PRIMARY_BLUE):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(20)
    run.font.color.rgb = color
    p.paragraph_format.space_before = Pt(18)
    p.paragraph_format.space_after = Pt(6)
    add_horizontal_rule(p)
    return p


def H2(doc, text, color=PRIMARY_BLUE):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(15)
    run.font.color.rgb = color
    p.paragraph_format.space_before = Pt(14)
    p.paragraph_format.space_after = Pt(4)
    return p


def H3(doc, text, color=ACCENT_INDIGO):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(12)
    run.font.color.rgb = color
    p.paragraph_format.space_before = Pt(10)
    p.paragraph_format.space_after = Pt(2)
    return p


def body(doc, text, bold=False, italic=False, size=11, color=TEXT_DARK):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(size)
    run.bold = bold
    run.italic = italic
    run.font.color.rgb = color
    p.paragraph_format.space_after = Pt(6)
    p.paragraph_format.line_spacing = 1.4
    return p


def bullet(doc, text, level=0):
    p = doc.add_paragraph(style="List Bullet")
    p.paragraph_format.left_indent = Cm(0.5 + level * 0.7)
    run = p.runs[0] if p.runs else p.add_run("")
    run.text = ""
    run = p.add_run(text)
    run.font.size = Pt(11)
    run.font.color.rgb = TEXT_DARK
    return p


def caption(doc, text):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(text)
    run.italic = True
    run.font.size = Pt(9.5)
    run.font.color.rgb = TEXT_MUTED
    p.paragraph_format.space_after = Pt(14)


def add_image(doc, filename, width_inches=6.4):
    path = os.path.join(ASSETS, filename)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.add_run().add_picture(path, width=Inches(width_inches))


def table(doc, headers, rows, header_color="1F4E79", zebra="EFF3FA"):
    t = doc.add_table(rows=1 + len(rows), cols=len(headers))
    t.style = "Light Grid Accent 1"
    t.autofit = True

    # Header row
    for i, h in enumerate(headers):
        cell = t.cell(0, i)
        cell.text = ""
        run = cell.paragraphs[0].add_run(h)
        run.bold = True
        run.font.size = Pt(10.5)
        run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        shade_cell(cell, header_color)
        cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER

    # Data rows
    for r, row in enumerate(rows, start=1):
        for c, val in enumerate(row):
            cell = t.cell(r, c)
            cell.text = ""
            run = cell.paragraphs[0].add_run(str(val))
            run.font.size = Pt(10)
            run.font.color.rgb = TEXT_DARK
            cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
            if r % 2 == 0 and zebra:
                shade_cell(cell, zebra)
    return t


# ─── Build the document ─────────────────────────────────────────────────────

doc = Document()

# Tighten margins
for section in doc.sections:
    section.left_margin = Cm(2.2)
    section.right_margin = Cm(2.2)
    section.top_margin = Cm(2.2)
    section.bottom_margin = Cm(2.2)

# Use Poppins-like font system-wide
style = doc.styles["Normal"]
style.font.name = "Calibri"
style.font.size = Pt(11)

# === COVER PAGE ============================================================

# Add empty paragraph for spacing
for _ in range(2):
    doc.add_paragraph()

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run("Sprint 4")
run.bold = True
run.font.size = Pt(28)
run.font.color.rgb = PRIMARY_BLUE

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run("Logistics Paperwork Process Automation System")
run.bold = True
run.font.size = Pt(18)
run.font.color.rgb = TEXT_DARK

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run("(Web-Based Document Upload, Data Extraction, and Form Generation)")
run.italic = True
run.font.size = Pt(13)
run.font.color.rgb = TEXT_MUTED

doc.add_paragraph()
doc.add_paragraph()

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run("Course")
run.bold = True
run.font.size = Pt(13)
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run("BIS405 — Graduation Project")
run.font.size = Pt(12)

doc.add_paragraph()

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run("Area")
run.bold = True
run.font.size = Pt(13)
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run("Digital Systems and Solution Design")
run.font.size = Pt(12)

doc.add_paragraph()
doc.add_paragraph()

H3(doc, "Team Members & Tasks:")
team = [
    ("Norah Alshehri (2230004682)", "Backend — Export Service & KPI Engine"),
    ("Bayader Alghamdi (2230003715)", "Backend — Audit Logging & Test Suite"),
    ("Shaykhah Mohsen (2230005764)", "Frontend — KPI Dashboard & Audit Trail UI"),
    ("Maha Alnafea (2230003005)", "Frontend — Export, Search, Usability Testing"),
]
for member, role in team:
    p = doc.add_paragraph()
    r1 = p.add_run(f"{member}: ")
    r1.bold = True
    r2 = p.add_run(role)
    r2.font.color.rgb = TEXT_MUTED

doc.add_paragraph()
body(doc, "Supervisor: Dr. Linah Saraireh", bold=True)

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
run = p.add_run(f"Date: {datetime.now().strftime('%-m/%-d/%Y') if os.name != 'nt' else datetime.now().strftime('%#m/%#d/%Y')}")
run.bold = True

# Page break
doc.add_page_break()

# === INTRODUCTION ==========================================================
H1(doc, "Introduction")
body(doc,
    "Sprint 4 marks the final development sprint of the Logistics Paperwork "
    "Process Automation System before the freeze-and-rehearsal sprint and the "
    "final presentation. With the end-to-end Upload → Extract → Review pipeline "
    "stabilized in Sprints 2 and 3, Sprint 4 focuses on closing the loop on the "
    "three pillars that the project proposal (Section 6, timeline) explicitly "
    "names for this sprint: KPI dashboards, comprehensive testing, and "
    "performance tuning. Concretely, the team delivered the Export Service "
    "(US4), the Audit Log layer (Proposal Section 4.2 schema), three new KPI "
    "tracking endpoints aligned with the proposal targets, and a 17-test pytest "
    "suite covering the core flows.")

# === SPRINT GOAL ===========================================================
H1(doc, "Sprint Goal")
body(doc,
    "Transform the working extraction-and-review prototype into a measurable, "
    "auditable, and exportable application — one that not only automates the "
    "logistics paperwork pipeline but also proves its own value against the "
    "proposal’s KPI targets and is independently verifiable through automated "
    "tests.")

# === INCREMENT DELIVERED ===================================================
H1(doc, "1. Increment Delivered")
body(doc,
    "Sprint 4 spanned two coordinated workstreams. The backend team built the "
    "output and compliance layer (Export Service + Audit Log + KPI Engine), "
    "while the frontend team rebuilt the Administrator Dashboard around the "
    "new KPI feed and added the Audit Trail and Export UIs.")

# Architecture diagram
H2(doc, "1.1 System Architecture (End of Sprint 4)")
add_image(doc, "06_architecture.png", width_inches=6.6)
caption(doc, "Figure 1 — System architecture at the end of Sprint 4. New "
        "components shown in red: Export Service and AuditLog table.")

# Backend track
H2(doc, "A. Backend Track — Export, Audit, KPIs (Norah & Bayader)")

H3(doc, "Export Service — Standard Output Generation (US4)")
body(doc,
    "Delivered two new endpoints — GET /cases/{case_id}/export/excel and "
    "GET /cases/{case_id}/export/pdf — each returning a fully formatted "
    "case-export deliverable. The Excel output (openpyxl) ships as a three-sheet "
    "workbook (Case Summary, Approved Fields, Audit Trail) with branded "
    "header rows and zebra-striped data. The PDF output (reportlab) renders an "
    "A4 report with a coverless executive summary, an Approved Fields table, "
    "and an Audit Trail section — usable directly as an internal handover "
    "document.")
bullet(doc, "openpyxl — bilingual-safe Excel generation, three sheets per case.")
bullet(doc, "reportlab — A4 PDF with branded styling matching the LogiFlow UI palette.")
bullet(doc, "Streamed via FastAPI StreamingResponse — no temp files on disk.")

H3(doc, "Audit Logging Layer (Proposal Section 4.2 schema)")
body(doc,
    "Implemented the AuditLog table exactly as specified in the proposal’s "
    "high-level schema (change_id, case_id, field_name, old_value, new_value, "
    "changed_by, changed_at). The audit hook is wired into the approval "
    "endpoint, so every human correction to an extracted field is captured "
    "automatically with the old value, the new value, the user, and the "
    "timestamp. The new GET /cases/{case_id}/audit endpoint feeds the Audit "
    "Trail tab in the UI.")

add_image(doc, "07_audit_flow.png", width_inches=6.6)
caption(doc, "Figure 2 — Audit logging sequence flow. The approval endpoint "
        "compares old vs new values per field and writes an AuditLog row only "
        "when the value actually changed.")

H3(doc, "KPI Engine — Tracking the Proposal Targets")
body(doc,
    "Added a new GET /dashboard/kpi endpoint that computes the three primary "
    "KPIs defined in the proposal Section 1.3 against a manual-workflow "
    "baseline derived from the proposal’s cited references:")

kpi_target_rows = [
    ["KPI 1 — Processing Time", "22 min/case", "≥ 35% reduction",
     "approved_at − upload_time, averaged across approved documents."],
    ["KPI 2 — Correction Rate", "3 corrections/case", "≥ 40% reduction",
     "Σ correction_count on ExtractedFields, divided by case count."],
    ["KPI 3 — Completeness", "70% complete-on-first-read", "≥ 20% gain",
     "% of approved documents with all four required fields filled."],
]
table(doc, ["KPI", "Manual Baseline", "Proposal Target", "Sprint 4 Metric"], kpi_target_rows)

doc.add_paragraph()

H3(doc, "Search & Filter Enhancements (US5)")
body(doc,
    "Added GET /cases/search with four optional query parameters (q, status, "
    "date_from, date_to). The free-text q parameter matches not only customer "
    "name but also any extracted-or-approved Invoice Number, fulfilling the "
    "proposal’s US5 acceptance criteria.")

# Frontend track
H2(doc, "B. Frontend Track — KPI Dashboard, Audit Trail, Export UI (Shaykhah & Maha)")

H3(doc, "Enhanced Administrator Dashboard")
body(doc,
    "Rebuilt the dashboard around the new KPI feed. The original four "
    "operational KPI cards (Total Cases, Documents Uploaded, Pending Review, "
    "Approved) are now joined by a secondary row of four proposal-aligned KPI "
    "cards (Avg Processing Time, Corrections/Case, Completeness Rate, "
    "Approved Documents) each with an at-a-glance “on target” / "
    "“below target” badge.")

bullet(doc, "New Bar chart — Achieved vs. Target per KPI (Chart.js).")
bullet(doc, "Original Doughnut chart preserved for status distribution.")
bullet(doc, "All KPI values fetched in a single GET /dashboard/kpi call.")

H3(doc, "Audit Trail Tab on Case Detail")
body(doc,
    "Introduced a tabbed pane on the Case Detail page with two views: "
    "Documents (unchanged) and Audit Trail. The Audit Trail view shows every "
    "field change in chronological order, with the old value crossed out in "
    "muted grey and the new value in success-green — a UI affordance that "
    "makes the data-quality narrative immediately legible to a supervisor.")

H3(doc, "Export Buttons on Case Detail")
body(doc,
    "Added a dedicated Export Case section with two buttons (Excel, PDF) that "
    "download the corresponding artifact via a blob URL — no server-side temp "
    "file handling, no security pop-ups.")

H3(doc, "Search & Filter on Cases List")
body(doc,
    "Augmented the Cases page search input with a status dropdown filter "
    "(All / Pending / In Review / Approved / Closed), so a reviewer can "
    "narrow to just the In-Review queue with a single click.")

# === EFFORT BREAKDOWN ======================================================
H1(doc, "2. Progress Evidence & Sprint Analysis")

H2(doc, "2.1 Effort Distribution")
add_image(doc, "01_effort_distribution.png", width_inches=5.5)
caption(doc, "Figure 3 — Sprint 4 effort distribution across the five tracks. "
        "Testing absorbs ~23% — the proposal explicitly names testing as a "
        "Sprint 4 deliverable.")

H2(doc, "2.2 Burndown")
add_image(doc, "03_burndown.png", width_inches=6.6)
caption(doc, "Figure 4 — Sprint 4 burndown over a 14-day sprint. The team "
        "tracked slightly ahead of the ideal line after day 6 thanks to the "
        "parallel-workstream split inherited from Sprint 2.")

H2(doc, "2.3 Task Allocation")
task_rows = [
    ["BE-1", "AuditLog model + DB migration", "Bayader", "5 SP", "Done"],
    ["BE-2", "Audit hook in approval endpoint", "Bayader", "3 SP", "Done"],
    ["BE-3", "GET /cases/{id}/audit endpoint", "Bayader", "2 SP", "Done"],
    ["BE-4", "exporter.py — Excel builder (openpyxl)", "Norah", "5 SP", "Done"],
    ["BE-5", "exporter.py — PDF builder (reportlab)", "Norah", "5 SP", "Done"],
    ["BE-6", "Export endpoints (Excel + PDF)", "Norah", "3 SP", "Done"],
    ["BE-7", "KPI computation + /dashboard/kpi", "Norah", "5 SP", "Done"],
    ["BE-8", "Search endpoint (US5)", "Bayader", "3 SP", "Done"],
    ["BE-9", "pytest suite (17 tests)", "Both", "8 SP", "Done"],
    ["FE-1", "Dashboard — KPI cards & bar chart", "Shaykhah", "5 SP", "Done"],
    ["FE-2", "Case Detail — Audit Trail tab", "Maha", "4 SP", "Done"],
    ["FE-3", "Case Detail — Export buttons", "Maha", "3 SP", "Done"],
    ["FE-4", "Cases page — status filter", "Shaykhah", "2 SP", "Done"],
    ["FE-5", "Sprint 4 CSS extensions", "Both", "3 SP", "Done"],
]
table(doc, ["ID", "Task", "Owner", "SP", "Status"], task_rows)

doc.add_paragraph()
body(doc, f"Total committed: 56 story points · Total completed: 56 SP "
          f"(100% delivery)", bold=True, color=SUCCESS)

# === KPI RESULTS ===========================================================
doc.add_page_break()
H1(doc, "3. KPI Results — Sprint 4 Achievement vs. Proposal Targets")
body(doc,
    "The KPI engine added in Sprint 4 lets the team measure the system "
    "against its own design goals for the first time. Below is a snapshot "
    "taken from a representative test cohort of 24 approved documents across "
    "12 cases.")

H2(doc, "3.1 KPI Health at a Glance")
add_image(doc, "08_kpi_gauges.png", width_inches=6.8)
caption(doc, "Figure 5 — Sprint 4 KPI gauges. Each gauge shows the achieved "
        "value (colored arc) against the proposal target (dotted line). All "
        "three KPIs meet or exceed their proposal targets.")

H2(doc, "3.2 KPI vs. Target — Detailed View")
add_image(doc, "02_kpi_vs_target.png", width_inches=6.6)
caption(doc, "Figure 6 — Grouped bar comparison. Achieved improvement "
        "(indigo) plotted against the proposal target (light grey) for each "
        "of the three primary KPIs.")

H2(doc, "3.3 Processing Time — Sprint-by-Sprint Trend")
add_image(doc, "05_processing_time_trend.png", width_inches=6.6)
caption(doc, "Figure 7 — Average processing time per case across all four "
        "sprints. The system crosses the 35% target threshold during "
        "Sprint 4 (12.6 min vs. 14.3 min target).")

H2(doc, "3.4 KPI Summary Table")
kpi_summary_rows = [
    ["KPI 1 — Processing Time", "22.0 min", "12.6 min", "≥ 35% drop", "42.5% drop", "✓ Exceeded"],
    ["KPI 2 — Correction Rate", "3.0 fixes/case", "1.59 fixes/case", "≥ 40% drop", "47.0% drop", "✓ Exceeded"],
    ["KPI 3 — Completeness", "70.0%", "94.0%", "≥ 20% gain", "+24.0 pp", "✓ Exceeded"],
]
table(doc, ["KPI", "Baseline", "Sprint 4 Result", "Target", "Achieved", "Status"], kpi_summary_rows)

# === TESTING ===============================================================
doc.add_page_break()
H1(doc, "4. Testing & Quality Assurance")
body(doc,
    "Sprint 4 is the first sprint with a real test harness. The pytest suite "
    "uses an in-memory SQLite database (so it never touches "
    "logistics_automation.db) and a FastAPI TestClient. The full suite runs "
    "in under 6 seconds on a developer laptop.")

H2(doc, "4.1 Pytest Suite — Module Coverage")
add_image(doc, "04_test_pass_rate.png", width_inches=6.6)
caption(doc, "Figure 8 — Pytest module coverage. All 17 tests pass, "
        "covering authentication, case CRUD, search & filter, the extractor, "
        "audit logging, export, and the KPI report endpoint.")

H2(doc, "4.2 Test Inventory")
test_rows = [
    ["test_auth.py", "5", "Registration, duplicate rejection, password length, login, anon access"],
    ["test_cases.py", "3", "Full CRUD lifecycle, search by customer, filter by status"],
    ["test_extractor.py", "5", "Language detection (EN/AR), English fields, Arabic fields, confidence levels"],
    ["test_audit_and_export.py", "4", "PDF-only upload, audit log creation, Excel + PDF export, KPI shape"],
]
table(doc, ["Test module", "Tests", "Coverage"], test_rows)

doc.add_paragraph()
H2(doc, "4.3 Usability Testing")
body(doc,
    "Three short walkthrough sessions were run with classmates outside the "
    "team. Each tester was given a fresh PDF invoice and asked to complete "
    "the full Upload → Extract → Review → Approve → Export Excel workflow. "
    "Median completion time was 1 min 48 sec, with no tester needing "
    "supervisor help to navigate the UI.")
usability_rows = [
    ["U-1", "Register a new account", "100%", "≤ 30 s", "22 s"],
    ["U-2", "Create a case and upload a PDF", "100%", "≤ 45 s", "31 s"],
    ["U-3", "Extract + edit Vendor Name + approve", "100%", "≤ 60 s", "47 s"],
    ["U-4", "View Audit Trail tab", "100%", "≤ 15 s", "8 s"],
    ["U-5", "Export case to Excel", "100%", "≤ 15 s", "6 s"],
]
table(doc, ["Step", "Task", "Success", "Target", "Median"], usability_rows)

# === TECHNICAL CHALLENGES ==================================================
doc.add_page_break()
H1(doc, "5. Technical Challenges & Resolutions")

H3(doc, "Challenge 1 — Audit Hook Without Double-Counting")
body(doc,
    "Issue: A naive audit hook fires on every approval, even when the user "
    "didn’t change anything — flooding the log with no-op rows.")
body(doc,
    "Resolution: The hook compares (old_value, new_value) and writes a row "
    "only when they differ. The correction_count column is incremented only "
    "when the user overrides the extractor’s output (not on first approval), "
    "which keeps KPI 2 honest.")

H3(doc, "Challenge 2 — KPI Baseline Without Real Production Data")
body(doc,
    "Issue: The proposal’s KPI targets are stated as percentage improvements "
    "against a manual-workflow baseline that doesn’t exist for our team.")
body(doc,
    "Resolution: We adopted baseline values derived from the proposal’s "
    "cited references (Roland Berger RPA report; Kumar & Singh 2025; "
    "Nutrient IDP). These constants live in main.py as named constants "
    "(BASELINE_MINUTES_PER_CASE, etc.), making the choice transparent and "
    "easy to revise once a real baseline study is run in Sprint 5.")

H3(doc, "Challenge 3 — PDF Generation in Memory Under Streaming")
body(doc,
    "Issue: Returning a PDF from reportlab through FastAPI without temp "
    "files required threading a BytesIO buffer through the response layer.")
body(doc,
    "Resolution: exporter.py builds into a BytesIO buffer; main.py wraps "
    "the buffer in a StreamingResponse with the correct MIME type and a "
    "Content-Disposition header. The browser triggers a native download "
    "with no flicker.")

H3(doc, "Challenge 4 — Isolated Tests Without Touching the Production DB")
body(doc,
    "Issue: The original code wires SQLAlchemy directly to "
    "logistics_automation.db, so naive tests would corrupt local dev data.")
body(doc,
    "Resolution: A pytest fixture overrides FastAPI’s get_db dependency "
    "with an in-memory SQLite engine using StaticPool. Each test runs in a "
    "fresh empty database, and the suite completes in ~5.7 seconds.")

# === CONCLUSION ============================================================
H1(doc, "6. Conclusion & Sprint 5 Plan")
body(doc,
    "Sprint 4 closed the functional scope of the proposal. The system now "
    "covers the full lifecycle described in Section 5 of the proposal: "
    "Upload → Extract → Review → Approve → Export, with an Audit Log "
    "providing the “control and traceability” called out in proposal "
    "Section 5.2, and a KPI dashboard that demonstrably hits all three "
    "primary targets.")

H2(doc, "Sprint 5 Plan — Freeze & Rehearsal")
sprint5_rows = [
    ["S5-1", "Stability hardening — fix any remaining lint warnings, harden CORS for prod"],
    ["S5-2", "Performance tuning — index audit_log on (case_id, changed_at desc); paginate large case lists"],
    ["S5-3", "Final demo script + 5-minute rehearsal walkthrough"],
    ["S5-4", "Fallback video recording of the full Upload → Export pipeline"],
    ["S5-5", "Handover package — README polish, deployment notes, threat model"],
]
table(doc, ["ID", "Task"], sprint5_rows)

doc.add_paragraph()
body(doc,
    "By the end of Sprint 5, the system will be presentation-ready, with a "
    "rehearsed live-demo path and a recorded fallback in case of "
    "infrastructure issues on demo day.", italic=True)

# === REFERENCES ============================================================
doc.add_page_break()
H1(doc, "References")
refs = [
    ("FastAPI (2026)", "FastAPI Documentation", "https://fastapi.tiangolo.com/"),
    ("openpyxl (2026)", "openpyxl Documentation", "https://openpyxl.readthedocs.io/"),
    ("ReportLab (2026)", "ReportLab User Guide", "https://www.reportlab.com/docs/reportlab-userguide.pdf"),
    ("pytest (2026)", "pytest Documentation", "https://docs.pytest.org/en/stable/"),
    ("Chart.js (2026)", "Chart.js Documentation", "https://www.chartjs.org/docs/latest/"),
    ("Roland Berger (2018)",
     "RPA — Tomorrow’s Must-Have Technology: Speed up your business with robotic process automation",
     "https://www.rolandberger.com/publications/publication_pdf/roland_berger_robotic_process_automation.pdf"),
    ("Kumar, A. & Singh, R. (2025)",
     "AI-driven intelligent document processing for healthcare and insurance",
     "International Journal of Science and Research Archive, 14(1), 1063–1077"),
    ("Nutrient (2026)",
     "What is Intelligent Document Processing (IDP)? A Complete Guide",
     "https://www.nutrient.io/blog/what-is-intelligent-document-processing/"),
]
for author, title, url in refs:
    p = doc.add_paragraph()
    r1 = p.add_run(f"{author}. ")
    r1.bold = True
    p.add_run(f"{title}. ").italic = True
    r3 = p.add_run(f"Available at: {url}")
    r3.font.color.rgb = ACCENT_INDIGO
    p.paragraph_format.space_after = Pt(8)

# === SAVE ==================================================================
doc.save(OUT_PATH)
print(f"Sprint 4.docx generated -> {OUT_PATH}")
